#######################
# Theme Customization #
#######################

title: Ho!                            # used in <title> tag & site header
author: 이 호 성                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Hello 911 emergency, there's a handsome guy in my house!
  Oh wait a second, cancel that. It's only me.
slogan: Do our best!!                    # used in site header, beside title
avatar: /i/avatar.jpg                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/soh9646/soh9646.github.io # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/rlue/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Portfolio
    url: /portfolio
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: 버스 이용객 승·하차 인식을 위한 IoT 시스템
    teaser: Yolov3를 이용한 얼굴 인식 및 IoT 기기들을 이용해 승·하차 인식
    url: https://github.com/soh9646/
    role: Creator
    category: IoT system

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
